### Student Information
Name: 陳剛頡

Student ID: R13944050

GitHub ID: R13944050

Kaggle name: r13944050_豬股頡

Kaggle private scoreboard snapshot: ![Alt text](./img/pic0.png "Image Title")

---

### Instructions

1. First: __This part is worth 30% of your grade.__ Do the **take home exercises** in the [DM2024-Lab2-master Repo](https://github.com/didiersalazar/DM2024-Lab2-Master). You may need to copy some cells from the Lab notebook to this notebook. 


2. Second: __This part is worth 30% of your grade.__ Participate in the in-class [Kaggle Competition](https://www.kaggle.com/competitions/dm-2024-isa-5810-lab-2-homework) regarding Emotion Recognition on Twitter by this link: https://www.kaggle.com/competitions/dm-2024-isa-5810-lab-2-homework. The scoring will be given according to your place in the Private Leaderboard ranking: 
    - **Bottom 40%**: Get 20% of the 30% available for this section.

    - **Top 41% - 100%**: Get (0.6N + 1 - x) / (0.6N) * 10 + 20 points, where N is the total number of participants, and x is your rank. (ie. If there are 100 participants and you rank 3rd your score will be (0.6 * 100 + 1 - 3) / (0.6 * 100) * 10 + 20 = 29.67% out of 30%.)   
    Submit your last submission **BEFORE the deadline (Nov. 26th, 11:59 pm, Tuesday)**. Make sure to take a screenshot of your position at the end of the competition and store it as '''pic0.png''' under the **img** folder of this repository and rerun the cell **Student Information**.
    

3. Third: __This part is worth 30% of your grade.__ A report of your work developing the model for the competition (You can use code and comment on it). This report should include what your preprocessing steps, the feature engineering steps and an explanation of your model. You can also mention different things you tried and insights you gained. 


4. Fourth: __This part is worth 10% of your grade.__ It's hard for us to follow if your code is messy :'(, so please **tidy up your notebook**.


Upload your files to your repository then submit the link to it on the corresponding e-learn assignment.

Make sure to commit and save your changes to your repository __BEFORE the deadline (Nov. 26th, 11:59 pm, Tuesday)__. 

In [2]:
### Begin Assignment Here

# **Master**

---
### **>>> Exercise 1 (Take home):**  
Plot word frequency for Top 30 words in both train and test dataset. (Hint: refer to DM lab 1)


In [ ]:
# Answer here
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
import matplotlib.pyplot as plt
import numpy as np


def create_term_document_df(df):
    count_vect = CountVectorizer()  # Initialize the CountVectorizer
    X_counts = count_vect.fit_transform(df['text'])  # Transform the text data into word counts
    
    # Get the unique words (vocabulary) from the vectorizer
    words = count_vect.get_feature_names_out()
    
    # Create a DataFrame where rows are documents and columns are words
    term_document_df = pd.DataFrame(X_counts.toarray(), columns=words)
    
    return term_document_df


train_term_doc_dfs = create_term_document_df(train_df)
test_term_doc_dfs = create_term_document_df(test_df)

train_word_counts = train_term_doc_dfs.sum(axis=0).to_numpy()
test_word_counts = test_term_doc_dfs.sum(axis=0).to_numpy()

train_sort_idx = np.argsort(train_word_counts)[::-1]
test_sort_idx = np.argsort(test_word_counts)[::-1]

# Visualize the frequency distribution
fig, axes = plt.subplots(2, 1, figsize=(10, 6))
axes[0].bar(train_term_doc_dfs.columns[train_sort_idx[:30]], train_word_counts[train_sort_idx[:30]], align="center")
axes[0].set_title(f'Top 30 Term Frequency Distribution for Training dataset')
axes[0].set_xlabel('Word')
axes[0].set_ylabel('Term Frequency')
axes[0].grid(axis='y')

axes[1].bar(test_term_doc_dfs.columns[test_sort_idx[:30]], test_word_counts[test_sort_idx[:30]], align="center")
axes[1].set_title(f'Top 30 Term Frequency Distribution for Testing dataset')
axes[1].set_xlabel('Word')
axes[1].set_ylabel('Term Frequency')
axes[1].grid(axis='y')

plt.tight_layout()
plt.show()

---
### **>>> Exercise 2 (Take home):**  
Generate an embedding using the TF-IDF vectorizer instead of th BOW one with 1000 features and show the feature names for features [100:110].

In [ ]:
# Answer here
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf1000 = TfidfVectorizer(max_features=1000, tokenizer=nltk.word_tokenize) 

# apply analyzer to training data
tfidf1000.fit(train_df['text'])

train_data_tfidf1000 = tfidf1000.transform(train_df['text'])

## check dimension
print(train_data_tfidf1000.shape)

feature_names = tfidf1000.get_feature_names_out()
print(feature_names[100:110])

---
### **>>> Exercise 3 (Take home):**  
Can you interpret the results above? What do they mean?

The diagonal element has highest number in each row that represents that the model can classify the correct label in most of the cases. 
In some cases, model is vulernable to predict the wrong labels, such like predicting anger for the sample that has fear as the ground truth label.

---
### **>>> Exercise 4 (Take home):**  
Build a model using a ```Naive Bayes``` model and train it. What are the testing results? 

*Reference*: https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.MultinomialNB.html

In [ ]:
# Answer here
from sklearn.naive_bayes import MultinomialNB

NB_model = MultinomialNB()
## training!
NB_model = NB_model.fit(X_train, y_train)

## predict!
y_train_pred = NB_model.predict(X_train)
y_test_pred = NB_model.predict(X_test)

acc_train = accuracy_score(y_true=y_train, y_pred=y_train_pred)
acc_test = accuracy_score(y_true=y_test, y_pred=y_test_pred)

print('training accuracy: {}'.format(round(acc_train, 2)))
print('testing accuracy: {}'.format(round(acc_test, 2)))

print(classification_report(y_true=y_test, y_pred=y_test_pred))

cm = confusion_matrix(y_true=y_test, y_pred=y_test_pred) 
plot_confusion_matrix(cm, classes=my_tags, title='Confusion matrix')

---
### **>>> Exercise 5 (Take home):**  

How do the results from the Naive Bayes model and the Decision Tree model compare? How do you interpret these differences? Use the theoretical background covered in class to try and explain these differences.

For the testing results, NB model get a better performance than DT model in almost all the metrics. 
However, DT gets significant accuracy for training, which implies that DT model is vulernable to overfitting if we don't do some techniques like pruning or regularization.
Futhermore, NB is a model based on statistics and probability, on the other hand, DT utilize the greedy algorithm to find the best classifier which may not be able to handle the testing situation well.

---
### **>>> Exercise 6 (Take home):**  

Plot the Training and Validation Accuracy and Loss (different plots), just like the images below.(Note: the pictures below are an example from a different model). How to interpret the graphs you got? How are they related to the concept of overfitting/underfitting covered in class?

In [ ]:
# Answer here
from scipy.ndimage import gaussian_filter1d

train_acc = training_log["accuracy"].to_numpy()
val_acc = training_log["val_accuracy"].to_numpy()
train_loss = training_log["loss"].to_numpy()
val_loss = training_log["val_loss"].to_numpy()
epochs = training_log["epoch"].to_numpy()

smoothed_train_acc = gaussian_filter1d(train_acc, sigma=5)
smoothed_val_acc = gaussian_filter1d(val_acc, sigma=5)
smoothed_train_loss = gaussian_filter1d(train_loss, sigma=5)
smoothed_val_loss = gaussian_filter1d(val_loss, sigma=5)

fig, axes = plt.subplots(nrows=2, ncols=1, figsize=(8, 12))

axes[0].set(title="Accuracy per epoch",
            xlabel="Epochs",
            ylabel="Accuracy",
            xlim=(0, 25),
            ylim=(0.0, 1.0))

axes[1].set(title="Loss per epoch",
            xlabel="Epochs",
            ylabel="Loss",
            xlim=(0, 25),
            ylim=(0.0, 2.0))

axes[0].plot(epochs, smoothed_train_acc)
axes[0].plot(epochs, smoothed_val_acc)
axes[1].plot(epochs, smoothed_train_loss)
axes[1].plot(epochs, smoothed_val_loss)
axes[0].legend(["train", "val"])
axes[1].legend(["train", "val"])

# plt.tight_layout()
plt.show()

The plot indicates that the model suffers overfitting with little improvement for validation accuracy. It implies that maybe we need to implement some regularizations or enlarge the size of the dataset.

---
### **>>> Exercise 7 (Take home):**  

Now, we have the word vectors, but our input data is a sequence of words (or say sentence). 
How can we utilize these "word" vectors to represent the sentence data and train our model?

We can sum the vectors of the words and take the average as the representation of the sentence. 


### **>>> Exercise 8 (Take home):**  

Generate a t-SNE and UMAP visualization to show the 15 words most related to the words "angry", "happy", "sad", "fear" (60 words total). Compare the differences between both graphs.

In [ ]:
# Answer here

word_list = ['happy', 'angry', 'data', 'mining']

topn = 15
happy_words = ['happy'] + [word_ for word_, sim_ in w2v_google_model.most_similar('happy', topn=topn)]
angry_words = ['angry'] + [word_ for word_, sim_ in w2v_google_model.most_similar('angry', topn=topn)]        
data_words = ['data'] + [word_ for word_, sim_ in w2v_google_model.most_similar('data', topn=topn)]        
mining_words = ['mining'] + [word_ for word_, sim_ in w2v_google_model.most_similar('mining', topn=topn)]        

print('happy_words: ', happy_words)
print('angry_words: ', angry_words)
print('data_words: ', data_words)
print('mining_words: ', mining_words)

target_words = happy_words + angry_words + data_words + mining_words
print('\ntarget words: ')
print(target_words)

print('\ncolor list:')
cn = topn + 1
color = ['b'] * cn + ['g'] * cn + ['r'] * cn + ['y'] * cn
print(color)


## w2v model
model = w2v_google_model

## prepare training word vectors
size = 200
target_size = len(target_words)
all_word = list(model.index_to_key)
word_train = target_words + all_word[:size]
X_train = model[word_train]

## t-SNE model
tsne = TSNE(n_components=2, metric='cosine', random_state=28)

## training
X_tsne = tsne.fit_transform(X_train)

## UMAP model
umap_model = umap.UMAP(n_components=2, metric='cosine', random_state=28)

## training
X_umap = umap_model.fit_transform(X_train)

## plot the result
fig, axes = plt.subplots(1, 2, figsize=(20, 10))

axes[0].scatter(X_tsne[:target_size, 0], X_tsne[:target_size, 1], c=color)
for label, x, y in zip(target_words, X_tsne[:target_size, 0], X_tsne[:target_size, 1]):
    axes[0].annotate(label, xy=(x,y), xytext=(0,0),  textcoords='offset points')

## plot the result
axes[1].scatter(X_umap[:target_size, 0], X_umap[:target_size, 1], c=color)
for label, x, y in zip(target_words, X_umap[:target_size, 0], X_umap[:target_size, 1]):
    axes[1].annotate(label, xy=(x,y), xytext=(0,0),  textcoords='offset points')

axes[0].set(title = "t-sne")
axes[1].set(title = "umap")

plt.tight_layout()
plt.show()

Both methods have good performance on reducing the dimensions of the data points into 2D, however, umap shows a more tight clustering result comparing to t-sne.


### **>>> Exercise 9 (Take home):**  

You noticed there is a **role** parameter inside the ollama.chat function, investigate what other roles there can be inside the function and what do they do. Give an example of a prompt using another role in additional to the **user** one.

In [ ]:
response = ollama.chat(model='llama3.2', messages=[
    {
        'role': 'system',
        'content': 'Respond in 100 words.'
    },
    {
        'role': 'user',
        'content': 'What is data mining? (in markdown format)'
    },
])

print(response['message']['content'])

### **>>> Exercise 10 (Take home):**  

Try asking the model with one image of your choosing. Is the description accurate? Why?

In [ ]:
# Answer here
response3 = ollama.chat(model='llava-phi3', messages=[
    {
        'role': 'user',
        'content': 'What is this image about?',
        'images': ['./pics/sample2.gif'] #Image with the cat
    },
])

display(Markdown(response3['message']['content']))

The description is amazingly accurate and contains so many details and subject explanation.

### **>>> Exercise 11 (Take home):**  

Try to modify the code to make it accept **three URLs**, or **three text documents** of your choosing. After modifying it, make **three prompts/questions** with information that can be found in each of the documents/urls, **compare the accuracy of the response** with the actual answer. Investigate and discuss the advantages and disadvantages of RAG systems.

In [ ]:
# Answer here
llm_model = "llama3.2" #You can change to the one of your preference
my_urls = ["https://en.wikipedia.org/wiki/Sword_Art_Online", "https://bandori.fandom.com/wiki/MyGO!!!!!#Background", "https://en.wikipedia.org/wiki/Bocchi_the_Rock%21"]

# Function to load, split, and retrieve documents
def load_and_retrieve_docs(urls):
    loader = WebBaseLoader(
        web_paths=urls,
        bs_kwargs=dict() 
    ) 
    docs = loader.load() #We will load the URL that will serve as our data source
    text_splitter = RecursiveCharacterTextSplitter(chunk_size=100, chunk_overlap=20) #We will divide the URL in chunks of text for easier comparison in the vector space
    splits = text_splitter.split_documents(docs)
    #print(splits) #You can print this to see how the chunks in the url where split
    embeddings = OllamaEmbeddings(model=llm_model) #Generating embeddings with our chosen model
    vectorstore = Chroma.from_documents(documents=splits, embedding=embeddings) #Our vector space for comparison
    return vectorstore.as_retriever()

# Create the retriever
retriever = load_and_retrieve_docs(my_urls)

def format_docs(docs):
    return "\n\n".join(doc.page_content for doc in docs) #Format the retrieved docs in an orderly manner for prompting

# Define the Ollama LLM function
def ollama_llm(question, context):
    formatted_prompt = f"Question: {question}\n\nContext: {context}"
    response = ollama.chat(model='llama3.2', messages=[{'role': 'user', 'content': formatted_prompt}])
    return response['message']['content']

# Define the RAG chain
def rag_chain(question):
    retrieved_docs = retriever.invoke(question)
    formatted_context = format_docs(retrieved_docs)
    return ollama_llm(question, formatted_context)

# Use the RAG chain
result1 = rag_chain("Who are the main characters of SAO?")
result2 = rag_chain("What band that Tomori joined before is disbanded?")
result3 = rag_chain("What is the nickname of Hitori Goto?")

display(Markdown("### **Result1**"))
display(Markdown(result1))
display(Markdown("### **Result2**"))
display(Markdown(result2))
display(Markdown("### **Result3**"))
display(Markdown(result3))


### **Comparison**
The performance of question 2 and 3 are worse than that of question 1 since no valid information is responded by the model in question 2 and 3, however, it gives a acceptable answer for question 1.

### **RAG adventages**
- Dynamic update
- Small model can also perform well with sufficient retrieval augmentation data
- Enhance knowledge coverage

### **RAG disadventages**
- Time consuming for retrieval phrase
- Potential of bias if biased data are provided

### **>>> Exercise 12 (Take home):**

Follow Exercise 6 again and Plot the Training and Validation Accuracy and Loss for the results of this Neural Network. Compare the results of both KNN and the NN we just implemented. Discuss about why we obtained these results with the LLM Embeddings compared to the results of the other models implemented in this Lab.

In [ ]:
# Answer here
# Answer here
from scipy.ndimage import gaussian_filter1d

train_acc = training_log["accuracy"].to_numpy()
val_acc = training_log["val_accuracy"].to_numpy()
train_loss = training_log["loss"].to_numpy()
val_loss = training_log["val_loss"].to_numpy()
epochs = training_log["epoch"].to_numpy()

smoothed_train_acc = gaussian_filter1d(train_acc, sigma=5)
smoothed_val_acc = gaussian_filter1d(val_acc, sigma=5)
smoothed_train_loss = gaussian_filter1d(train_loss, sigma=5)
smoothed_val_loss = gaussian_filter1d(val_loss, sigma=5)

fig, axes = plt.subplots(nrows=2, ncols=1, figsize=(8, 12))

axes[0].set(title="Accuracy per epoch",
            xlabel="Epochs",
            ylabel="Accuracy",
            xlim=(0, 25),
            ylim=(0.0, 1.0))

axes[1].set(title="Loss per epoch",
            xlabel="Epochs",
            ylabel="Loss",
            xlim=(0, 25),
            ylim=(0.0, 3.5))

axes[0].plot(epochs, smoothed_train_acc)
axes[0].plot(epochs, smoothed_val_acc)
axes[1].plot(epochs, smoothed_train_loss)
axes[1].plot(epochs, smoothed_val_loss)
axes[0].legend(["train", "val"])
axes[1].legend(["train", "val"])

# plt.tight_layout()
plt.show()

The NN method outperforms KNN model in both training and testing dataset. However, NN models suffer overfitting which implies that some adjustment must be implemented and the model can get better performance. Futhermore, using the embeddings from GoogleNews amazingly outperforms from LLaMA-3.2, it's surprising since LLaMA-3.2 can generate dynamic embeddings corresponding to the context, but finally get worse results in this task.

### **>>> Exercise 13 (Take home):**

Compare and discuss the results of the zero-shot, 1-shot and 5-shot classification.

Zero-shot outperforms tha rest two settings in accuracy but performs equally well to 5-shot if considers f1-score. But obvisously, 1-shot is the worst setting among them.

---
# **Kaggle Competition**

In [1]:
import pandas as pd
import json

raw_data = pd.read_json("data/tweets_DM.json", orient="record", lines=True)
raw_data.head(5)

_score          _index                                            _source  \
0     391  hashtag_tweets  {'tweet': {'hashtags': ['Snapchat'], 'tweet_id...   
1     433  hashtag_tweets  {'tweet': {'hashtags': ['freepress', 'TrumpLeg...   
2     232  hashtag_tweets  {'tweet': {'hashtags': ['bibleverse'], 'tweet_...   
3     376  hashtag_tweets  {'tweet': {'hashtags': [], 'tweet_id': '0x1cd5...   
4     989  hashtag_tweets  {'tweet': {'hashtags': [], 'tweet_id': '0x2de2...   

            _crawldate   _type  
0  2015-05-23 11:42:47  tweets  
1  2016-01-28 04:52:09  tweets  
2  2017-12-25 04:39:20  tweets  
3  2016-01-24 23:53:05  tweets  
4  2016-01-08 17:18:59  tweets

In [2]:
# Data Extraction
dataset = raw_data.copy()
dataset["tweet_id"] = dataset["_source"].apply(lambda x: x["tweet"]["tweet_id"])
dataset["hashtags"] = dataset["_source"].apply(lambda x: x["tweet"]["hashtags"])
dataset["text"] = dataset["_source"].apply(lambda x: x["tweet"]["text"])

# train test split
data_id = pd.read_csv("./data/data_identification.csv")
emotion = pd.read_csv("./data/emotion.csv")
dataset = dataset.merge(data_id, how="left", on="tweet_id")
dataset = dataset.merge(emotion, how="left", on="tweet_id")
print(f"Original shape: {dataset.shape}")
train_dataset = dataset[dataset["identification"] == "train"]
test_dataset = dataset[dataset["identification"] == "test"]
print(f"train_dataset shape:{train_dataset.shape}")
print(f"test_dataset shape:{test_dataset.shape}")


Original shape: (1867535, 10)
train_dataset shape:(1455563, 10)
test_dataset shape:(411972, 10)


In [ ]:
# Convert the string label into numerical label
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit(train_dataset["emotion"])
train_dataset["labels"] = le.transform(train_dataset["emotion"])

/tmp/ipykernel_1898/1802826570.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_dataset["labels"] = le.transform(train_dataset["emotion"])


In [4]:
from datasets import Dataset

train_dataset = Dataset.from_pandas(train_dataset[["text", "labels"]]) 
test_dataset = Dataset.from_pandas(test_dataset[["text"]])

In [6]:
from transformers import BertTokenizer, AutoModel, AutoTokenizer

# Load tokenizer
tokenizer =  AutoTokenizer.from_pretrained("bert-base-uncased", use_fast=False)

# Tokenization function
def preprocess_function(examples):
    return tokenizer(examples["text"], truncation=True, padding='max_length', max_length=64)

# Tokenize dataset
tokenized_train_dataset = train_dataset.map(preprocess_function, batched=True)
print(tokenized_train_dataset[0])


Map:   0%|          | 0/1455563 [00:00<?, ? examples/s]

{'text': 'People who post "add me on #Snapchat" must be dehydrated. Cuz man.... that\'s <LH>', 'labels': 1, '__index_level_0__': 0, 'input_ids': [101, 2111, 2040, 2695, 1000, 5587, 2033, 2006, 1001, 10245, 7507, 2102, 1000, 2442, 2022, 2139, 10536, 7265, 3064, 1012, 12731, 2480, 2158, 1012, 1012, 1012, 1012, 2008, 1005, 1055, 1026, 1048, 2232, 1028, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}


In [6]:
tokenized_train_dataset.set_format("torch", columns=["input_ids", "attention_mask", "labels"])

In [ ]:
import torch
import accelerate
from transformers import BertForSequenceClassification, Trainer, TrainingArguments

model = BertForSequenceClassification.from_pretrained("bert-base-uncased", problem_type="single_label_classification", num_labels=8)

training_args = TrainingArguments(
    output_dir='./results',          # output directory
    num_train_epochs=1,              # total # of training epochs
    per_device_train_batch_size=64,  # batch size per device during training
    warmup_steps=500,                # number of warmup steps for learning rate scheduler
    weight_decay=0.01,               # strength of weight decay
    logging_dir='./logs',
    metric_for_best_model="f1_score",
    logging_steps=1000,
    save_strategy="epoch",
    save_total_limit=2,
)

trainer = Trainer(
    model=model,                         # the instantiated 🤗 Transformers model to be trained
    args=training_args,                  # training arguments, defined above
    train_dataset=tokenized_train_dataset         # training dataset
)

You are using a model of type roberta to instantiate a model of type bert. This is not supported for all configurations of models and can yield errors.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at vinai/bertweet-base and are newly initialized: ['classifier.bias', 'classifier.weight', 'embeddings.LayerNorm.bias', 'embeddings.LayerNorm.weight', 'embeddings.position_embeddings.weight', 'embeddings.token_type_embeddings.weight', 'embeddings.word_embeddings.weight', 'encoder.layer.0.attention.output.LayerNorm.bias', 'encoder.layer.0.attention.output.LayerNorm.weight', 'encoder.layer.0.attention.output.dense.bias', 'encoder.layer.0.attention.output.dense.weight', 'encoder.layer.0.attention.self.key.bias', 'encoder.layer.0.attention.self.key.weight', 'encoder.layer.0.attention.self.query.bias', 'encoder.layer.0.attention.self.query.weight', 'encoder.layer.0.attention.self.value.bias', 'encoder.layer.0.attention.self.value.weight', 'encoder.la

In [ ]:
# Training
trainer.train()

/work/r13944050/anaconda3/envs/lab2/lib/python3.10/site-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(


/work/r13944050/anaconda3/envs/lab2/lib/python3.10/site-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(
/work/r13944050/anaconda3/envs/lab2/lib/python3.10/site-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(


TrainOutput(global_step=34116, training_loss=1.128931567710566, metrics={'train_runtime': 8039.0576, 'train_samples_per_second': 543.184, 'train_steps_per_second': 4.244, 'total_flos': 1.4362325569713254e+17, 'train_loss': 1.128931567710566, 'epoch': 3.0})

In [11]:
from torch.utils.data import DataLoader, Dataset
import torch

# Example dataset
class TestDataset(Dataset):
    def __init__(self, texts, tokenizer, device):
        self.texts = texts
        self.tokenizer = tokenizer
        self.device = device
        
    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        # Tokenize each text
        item = self.tokenizer(self.texts[idx], truncation=True, padding='max_length', max_length=64, return_tensors="pt")
        return item


In [15]:
device = "cuda:0"
_test_dataset = TestDataset(test_dataset["text"], tokenizer, device) 
batch_size = 5000
test_dataloader = DataLoader(_test_dataset, batch_size=batch_size, shuffle=False)

In [ ]:
# Predicting

from tqdm import tqdm
model = model.to(device)
all_predictions = []

with torch.no_grad():
    for batch in tqdm(test_dataloader):
        input_ids = batch["input_ids"].squeeze(1).to(device)
        attention_mask = batch["attention_mask"].squeeze(1).to(device)
        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        predictions = torch.argmax(outputs.logits, dim=1)
        print(predictions)
        all_predictions.extend(predictions.cpu().tolist())

  1%|          | 1/83 [00:08<11:07,  8.14s/it]

tensor([4, 1, 1,  ..., 4, 4, 2], device='cuda:0')


  2%|▏         | 2/83 [00:13<08:44,  6.47s/it]

tensor([2, 5, 4,  ..., 5, 4, 4], device='cuda:0')


  4%|▎         | 3/83 [00:18<08:01,  6.02s/it]

tensor([3, 0, 1,  ..., 4, 4, 2], device='cuda:0')


  5%|▍         | 4/83 [00:24<07:38,  5.81s/it]

tensor([4, 3, 4,  ..., 4, 4, 4], device='cuda:0')


  6%|▌         | 5/83 [00:29<07:23,  5.69s/it]

tensor([2, 4, 4,  ..., 1, 4, 1], device='cuda:0')


  7%|▋         | 6/83 [00:35<07:12,  5.62s/it]

tensor([1, 2, 2,  ..., 1, 1, 4], device='cuda:0')


  8%|▊         | 7/83 [00:40<07:03,  5.57s/it]

tensor([5, 4, 5,  ..., 5, 5, 7], device='cuda:0')


 10%|▉         | 8/83 [00:46<06:55,  5.54s/it]

tensor([2, 4, 4,  ..., 5, 3, 2], device='cuda:0')


 11%|█         | 9/83 [00:51<06:48,  5.52s/it]

tensor([4, 5, 4,  ..., 4, 4, 2], device='cuda:0')


 12%|█▏        | 10/83 [00:57<06:41,  5.50s/it]

tensor([2, 2, 5,  ..., 4, 4, 4], device='cuda:0')


 13%|█▎        | 11/83 [01:02<06:35,  5.50s/it]

tensor([0, 4, 2,  ..., 4, 5, 2], device='cuda:0')


 14%|█▍        | 12/83 [01:08<06:29,  5.48s/it]

tensor([5, 5, 2,  ..., 4, 3, 1], device='cuda:0')


 16%|█▌        | 13/83 [01:13<06:23,  5.48s/it]

tensor([1, 2, 1,  ..., 1, 5, 4], device='cuda:0')


 17%|█▋        | 14/83 [01:19<06:18,  5.48s/it]

tensor([5, 4, 1,  ..., 5, 4, 4], device='cuda:0')


 18%|█▊        | 15/83 [01:24<06:12,  5.48s/it]

tensor([0, 1, 2,  ..., 5, 4, 4], device='cuda:0')


 19%|█▉        | 16/83 [01:30<06:07,  5.48s/it]

tensor([4, 1, 4,  ..., 4, 4, 4], device='cuda:0')


 20%|██        | 17/83 [01:35<06:01,  5.48s/it]

tensor([7, 4, 1,  ..., 4, 1, 7], device='cuda:0')


 22%|██▏       | 18/83 [01:41<05:56,  5.48s/it]

tensor([2, 1, 5,  ..., 4, 4, 1], device='cuda:0')


 23%|██▎       | 19/83 [01:46<05:50,  5.48s/it]

tensor([5, 4, 4,  ..., 7, 2, 4], device='cuda:0')


 24%|██▍       | 20/83 [01:52<05:45,  5.49s/it]

tensor([0, 4, 5,  ..., 5, 3, 4], device='cuda:0')


 25%|██▌       | 21/83 [01:57<05:39,  5.48s/it]

tensor([5, 4, 4,  ..., 4, 4, 4], device='cuda:0')


 27%|██▋       | 22/83 [02:03<05:34,  5.48s/it]

tensor([5, 6, 2,  ..., 4, 4, 4], device='cuda:0')


 28%|██▊       | 23/83 [02:08<05:28,  5.48s/it]

tensor([7, 5, 5,  ..., 2, 5, 2], device='cuda:0')


 29%|██▉       | 24/83 [02:13<05:23,  5.48s/it]

tensor([5, 2, 5,  ..., 4, 3, 5], device='cuda:0')


 30%|███       | 25/83 [02:19<05:17,  5.47s/it]

tensor([1, 1, 5,  ..., 4, 2, 7], device='cuda:0')


 31%|███▏      | 26/83 [02:24<05:12,  5.48s/it]

tensor([4, 2, 3,  ..., 2, 5, 6], device='cuda:0')


 33%|███▎      | 27/83 [02:30<05:06,  5.48s/it]

tensor([5, 4, 7,  ..., 4, 4, 2], device='cuda:0')


 34%|███▎      | 28/83 [02:35<05:01,  5.48s/it]

tensor([4, 2, 7,  ..., 5, 4, 4], device='cuda:0')


 35%|███▍      | 29/83 [02:41<04:55,  5.47s/it]

tensor([4, 1, 5,  ..., 4, 4, 5], device='cuda:0')


 36%|███▌      | 30/83 [02:46<04:50,  5.47s/it]

tensor([5, 4, 4,  ..., 1, 2, 2], device='cuda:0')


 37%|███▋      | 31/83 [02:52<04:44,  5.48s/it]

tensor([4, 3, 4,  ..., 7, 4, 2], device='cuda:0')


 39%|███▊      | 32/83 [02:57<04:39,  5.48s/it]

tensor([5, 2, 4,  ..., 4, 4, 4], device='cuda:0')


 40%|███▉      | 33/83 [03:03<04:34,  5.48s/it]

tensor([2, 2, 4,  ..., 4, 4, 4], device='cuda:0')


 41%|████      | 34/83 [03:08<04:28,  5.48s/it]

tensor([5, 5, 4,  ..., 1, 4, 1], device='cuda:0')


 42%|████▏     | 35/83 [03:14<04:22,  5.47s/it]

tensor([7, 5, 4,  ..., 5, 2, 7], device='cuda:0')


 43%|████▎     | 36/83 [03:19<04:17,  5.48s/it]

tensor([4, 2, 4,  ..., 1, 2, 2], device='cuda:0')


 45%|████▍     | 37/83 [03:25<04:12,  5.48s/it]

tensor([4, 4, 5,  ..., 5, 4, 2], device='cuda:0')


 46%|████▌     | 38/83 [03:30<04:06,  5.48s/it]

tensor([1, 1, 7,  ..., 2, 4, 5], device='cuda:0')


 47%|████▋     | 39/83 [03:36<04:01,  5.48s/it]

tensor([7, 4, 4,  ..., 1, 4, 4], device='cuda:0')


 48%|████▊     | 40/83 [03:41<03:55,  5.47s/it]

tensor([1, 4, 5,  ..., 4, 4, 4], device='cuda:0')


 49%|████▉     | 41/83 [03:47<03:50,  5.48s/it]

tensor([2, 4, 4,  ..., 4, 2, 4], device='cuda:0')


 51%|█████     | 42/83 [03:52<03:44,  5.48s/it]

tensor([4, 4, 4,  ..., 5, 2, 5], device='cuda:0')


 52%|█████▏    | 43/83 [03:58<03:39,  5.48s/it]

tensor([5, 7, 2,  ..., 2, 5, 4], device='cuda:0')


 53%|█████▎    | 44/83 [04:03<03:33,  5.47s/it]

tensor([5, 4, 4,  ..., 1, 4, 2], device='cuda:0')


 54%|█████▍    | 45/83 [04:08<03:28,  5.47s/it]

tensor([5, 5, 5,  ..., 4, 4, 7], device='cuda:0')


 55%|█████▌    | 46/83 [04:14<03:22,  5.48s/it]

tensor([4, 4, 2,  ..., 7, 2, 4], device='cuda:0')


 57%|█████▋    | 47/83 [04:19<03:17,  5.48s/it]

tensor([5, 4, 7,  ..., 5, 2, 4], device='cuda:0')


 58%|█████▊    | 48/83 [04:25<03:11,  5.47s/it]

tensor([4, 2, 5,  ..., 4, 5, 3], device='cuda:0')


 59%|█████▉    | 49/83 [04:30<03:05,  5.46s/it]

tensor([5, 2, 1,  ..., 5, 5, 4], device='cuda:0')


 60%|██████    | 50/83 [04:36<03:00,  5.46s/it]

tensor([4, 4, 2,  ..., 4, 4, 4], device='cuda:0')


 61%|██████▏   | 51/83 [04:41<02:54,  5.47s/it]

tensor([4, 4, 5,  ..., 4, 4, 0], device='cuda:0')


 63%|██████▎   | 52/83 [04:47<02:49,  5.47s/it]

tensor([7, 1, 1,  ..., 4, 2, 5], device='cuda:0')


 64%|██████▍   | 53/83 [04:52<02:44,  5.47s/it]

tensor([4, 7, 4,  ..., 4, 6, 1], device='cuda:0')


 65%|██████▌   | 54/83 [04:58<02:38,  5.47s/it]

tensor([1, 4, 4,  ..., 1, 2, 4], device='cuda:0')


 66%|██████▋   | 55/83 [05:03<02:33,  5.47s/it]

tensor([1, 4, 4,  ..., 5, 5, 5], device='cuda:0')


 67%|██████▋   | 56/83 [05:09<02:27,  5.47s/it]

tensor([5, 4, 3,  ..., 4, 4, 4], device='cuda:0')


 69%|██████▊   | 57/83 [05:14<02:22,  5.47s/it]

tensor([4, 1, 4,  ..., 5, 4, 4], device='cuda:0')


 70%|██████▉   | 58/83 [05:20<02:16,  5.47s/it]

tensor([4, 4, 4,  ..., 2, 4, 3], device='cuda:0')


 71%|███████   | 59/83 [05:25<02:11,  5.47s/it]

tensor([4, 4, 4,  ..., 4, 1, 2], device='cuda:0')


 72%|███████▏  | 60/83 [05:31<02:05,  5.47s/it]

tensor([5, 4, 2,  ..., 4, 4, 4], device='cuda:0')


 73%|███████▎  | 61/83 [05:36<02:00,  5.47s/it]

tensor([5, 4, 2,  ..., 4, 1, 4], device='cuda:0')


 75%|███████▍  | 62/83 [05:41<01:54,  5.47s/it]

tensor([4, 5, 4,  ..., 7, 4, 5], device='cuda:0')


 76%|███████▌  | 63/83 [05:50<02:05,  6.29s/it]

tensor([2, 2, 4,  ..., 4, 4, 2], device='cuda:0')


 77%|███████▋  | 64/83 [05:55<01:54,  6.05s/it]

tensor([4, 4, 4,  ..., 4, 7, 1], device='cuda:0')


 78%|███████▊  | 65/83 [06:01<01:45,  5.87s/it]

tensor([4, 5, 7,  ..., 1, 4, 4], device='cuda:0')


 80%|███████▉  | 66/83 [06:06<01:37,  5.76s/it]

tensor([5, 1, 7,  ..., 4, 4, 5], device='cuda:0')


 81%|████████  | 67/83 [06:12<01:30,  5.67s/it]

tensor([4, 4, 0,  ..., 1, 4, 4], device='cuda:0')


 82%|████████▏ | 68/83 [06:17<01:24,  5.61s/it]

tensor([5, 4, 2,  ..., 5, 1, 7], device='cuda:0')


 83%|████████▎ | 69/83 [06:23<01:18,  5.57s/it]

tensor([4, 2, 4,  ..., 1, 4, 5], device='cuda:0')


 84%|████████▍ | 70/83 [06:28<01:12,  5.54s/it]

tensor([7, 2, 1,  ..., 1, 4, 4], device='cuda:0')


 86%|████████▌ | 71/83 [06:33<01:06,  5.52s/it]

tensor([5, 4, 4,  ..., 4, 2, 1], device='cuda:0')


 87%|████████▋ | 72/83 [06:39<01:00,  5.50s/it]

tensor([4, 1, 4,  ..., 4, 2, 2], device='cuda:0')


 88%|████████▊ | 73/83 [06:44<00:54,  5.49s/it]

tensor([1, 2, 4,  ..., 3, 2, 4], device='cuda:0')


 89%|████████▉ | 74/83 [06:50<00:49,  5.48s/it]

tensor([5, 3, 4,  ..., 5, 4, 4], device='cuda:0')


 90%|█████████ | 75/83 [06:55<00:43,  5.47s/it]

tensor([2, 3, 7,  ..., 1, 5, 5], device='cuda:0')


 92%|█████████▏| 76/83 [07:01<00:38,  5.47s/it]

tensor([5, 7, 2,  ..., 4, 2, 4], device='cuda:0')


 93%|█████████▎| 77/83 [07:06<00:32,  5.47s/it]

tensor([5, 5, 5,  ..., 4, 2, 4], device='cuda:0')


 94%|█████████▍| 78/83 [07:12<00:27,  5.47s/it]

tensor([2, 1, 4,  ..., 4, 4, 4], device='cuda:0')


 95%|█████████▌| 79/83 [07:17<00:21,  5.47s/it]

tensor([5, 2, 5,  ..., 4, 5, 5], device='cuda:0')


 96%|█████████▋| 80/83 [07:23<00:16,  5.47s/it]

tensor([4, 4, 5,  ..., 4, 2, 4], device='cuda:0')


 98%|█████████▊| 81/83 [07:28<00:10,  5.47s/it]

tensor([5, 1, 1,  ..., 4, 7, 2], device='cuda:0')


 99%|█████████▉| 82/83 [07:34<00:05,  5.47s/it]

tensor([5, 5, 4,  ..., 2, 4, 1], device='cuda:0')


100%|██████████| 83/83 [07:36<00:00,  5.50s/it]

tensor([4, 5, 2,  ..., 5, 0, 5], device='cuda:0')


In [ ]:
# reform the prediciton into submission format
submission = dataset[dataset["identification"] == "test"]
submission["emotion"] = le.inverse_transform(all_predictions)
submission = submission[["tweet_id", "emotion"]]
submission.rename(columns={"tweet_id":"id"}, inplace=True)
submission.head(5)

/tmp/ipykernel_1494/1488382705.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  submission["emotion"] = le.inverse_transform(all_predictions)


id       emotion
2   0x28b412           joy
4   0x2de201  anticipation
9   0x218443  anticipation
30  0x2939d5           joy
33  0x26289a         trust

In [ ]:
submission.to_csv("submission.csv", index=False)